# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_on_simulators:
    strategy:
      matrix:
        platform: [iOS, tvOS, watchOS, visionOS]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: xcodebuild Test ${{ matrix.platform }}
      run: xcodebuild test -scheme ViewInspection -destination 'platform=${{ matrix.platform }}'
      
  test_on_macos:
    strategy:
      matrix:
        xcode-version: ['15', 'latest-stable', 'latest']

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode-version }}

    - name: Swift Test macOS
      run: swift test
